# Generated by Django 5.0.6 on 2024-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_alter_cruise_id_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
